export const cars = [
    {
        id: 1,
        bodyType: "sedan",
        brand: "Toyota",
        model: "Camry",
        year: 2021,
        name: "Toyota Camry",
        price: 28000,
        mileage: 15000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Київ",
        image: require("@/assets/cars/01.jpg")
    },
    {
        id: 2,
        bodyType: "crossover",
        brand: "Honda",
        model: "CR-V",
        year: 2020,
        name: "Honda CR-V",
        price: 32000,
        mileage: 20000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Львів",
        image: require("@/assets/cars/02.jpg")
    },
    {
        id: 3,
        bodyType: "minivan",
        brand: "Volkswagen",
        model: "Transporter",
        year: 2019,
        name: "VW Transporter",
        price: 25000,
        mileage: 30000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Одеса",
        image: require("@/assets/cars/03.jpg")
    },
    {
        id: 4,
        bodyType: "microvan",
        brand: "Mercedes-Benz",
        model: "Citan",
        year: 2021,
        name: "Mercedes Citan",
        price: 23000,
        mileage: 12000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Харків",
        image: require("@/assets/cars/04.jpg")
    },
    {
        id: 5,
        bodyType: "hatchback",
        brand: "Ford",
        model: "Focus",
        year: 2018,
        name: "Ford Focus",
        price: 18000,
        mileage: 40000,
        engineType: "бензин",
        transmission: "механіка",
        city: "Дніпро",
        image: require("@/assets/cars/05.jpg")
    },
    {
        id: 6,
        bodyType: "sedan",
        brand: "BMW",
        model: "3 Series",
        year: 2017,
        name: "BMW 3 Series",
        price: 35000,
        mileage: 50000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Луцьк",
        image: require("@/assets/cars/06.jpg")
    },
    {
        id: 7,
        bodyType: "crossover",
        brand: "Audi",
        model: "Q5",
        year: 2019,
        name: "Audi Q5",
        price: 45000,
        mileage: 25000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Чернівці",
        image: require("@/assets/cars/07.jpg")
    },
    {
        id: 8,
        bodyType: "minivan",
        brand: "Renault",
        model: "Kangoo",
        year: 2020,
        name: "Renault Kangoo",
        price: 22000,
        mileage: 18000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Запоріжжя",
        image: require("@/assets/cars/08.jpg")
    },
    {
        id: 9,
        bodyType: "microvan",
        brand: "Peugeot",
        model: "Rifter",
        year: 2021,
        name: "Peugeot Rifter",
        price: 24000,
        mileage: 10000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Івано-Франківськ",
        image: require("@/assets/cars/09.jpg")
    },
    {
        id: 10,
        bodyType: "hatchback",
        brand: "Kia",
        model: "Ceed",
        year: 2018,
        name: "Kia Ceed",
        price: 19000,
        mileage: 35000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Миколаїв",
        image: require("@/assets/cars/10.jpg")
    },
    {
        id: 11,
        bodyType: "sedan",
        brand: "Hyundai",
        model: "Elantra",
        year: 2019,
        name: "Hyundai Elantra",
        price: 21000,
        mileage: 28000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Полтава",
        image: require("@/assets/cars/11.jpg")
    },
    {
        id: 12,
        bodyType: "crossover",
        brand: "Mazda",
        model: "CX-5",
        year: 2021,
        name: "Mazda CX-5",
        price: 34000,
        mileage: 15000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Чернігів",
        image: require("@/assets/cars/12.jpg")
    },
    {
        id: 13,
        bodyType: "minivan",
        brand: "Opel",
        model: "Zafira",
        year: 2018,
        name: "Opel Zafira",
        price: 20000,
        mileage: 32000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Кропивницький",
        image: require("@/assets/cars/13.jpg")
    },
    {
        id: 14,
        bodyType: "microvan",
        brand: "Citroen",
        model: "Berlingo",
        year: 2020,
        name: "Citroen Berlingo",
        price: 23000,
        mileage: 24000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Рівне",
        image: require("@/assets/cars/14.jpg")
    },
    {
        id: 15,
        bodyType: "hatchback",
        brand: "Nissan",
        model: "Leaf",
        year: 2019,
        name: "Nissan Leaf",
        price: 25000,
        mileage: 15000,
        engineType: "електро",
        transmission: "автомат",
        city: "Тернопіль",
        image: require("@/assets/cars/15.jpg")
    },
    {
        id: 16,
        bodyType: "sedan",
        brand: "Skoda",
        model: "Octavia",
        year: 2020,
        name: "Skoda Octavia",
        price: 22000,
        mileage: 27000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Житомир",
        image: require("@/assets/cars/16.jpg")
    },
    {
        id: 17,
        bodyType: "crossover",
        brand: "Subaru",
        model: "Forester",
        year: 2019,
        name: "Subaru Forester",
        price: 32000,
        mileage: 31000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Ужгород",
        image: require("@/assets/cars/17.jpg")
    },
    {
        id: 18,
        bodyType: "minivan",
        brand: "Fiat",
        model: "Doblo",
        year: 2021,
        name: "Fiat Doblo",
        price: 21000,
        mileage: 13000,
        engineType: "дизель",
        transmission: "механіка",
        city: "Суми",
        image: require("@/assets/cars/18.jpg")
    },
    {
        id: 19,
        bodyType: "microvan",
        brand: "Ford",
        model: "Tourneo",
        year: 2020,
        name: "Ford Tourneo",
        price: 24000,
        mileage: 19000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Хмельницький",
        image: require("@/assets/cars/19.jpg")
    },
    {
        id: 20,
        bodyType: "hatchback",
        brand: "Chevrolet",
        model: "Spark",
        year: 2018,
        name: "Chevrolet Spark",
        price: 15000,
        mileage: 45000,
        engineType: "бензин",
        transmission: "механіка",
        city: "Черкаси",
        image: require("@/assets/cars/20.jpg")
    },
    {
        id: 21,
        bodyType: "sedan",
        brand: "Volkswagen",
        model: "Passat",
        year: 2021,
        name: "VW Passat",
        price: 28000,
        mileage: 17000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Кременчук",
        image: require("@/assets/cars/21.jpg")
    },
    {
        id: 22,
        bodyType: "crossover",
        brand: "Mitsubishi",
        model: "Outlander",
        year: 2019,
        name: "Mitsubishi Outlander",
        price: 33000,
        mileage: 27000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Біла Церква",
        image: require("@/assets/cars/22.jpg")
    },
    {
        id: 23,
        bodyType: "minivan",
        brand: "Toyota",
        model: "Sienna",
        year: 2020,
        name: "Toyota Sienna",
        price: 35000,
        mileage: 22000,
        engineType: "бензин",
        transmission: "автомат",
        city: "Кривий Ріг",
        image: require("@/assets/cars/23.jpg")
    }
];


export const trucks = [
    {
        id: 1,
        bodyType: "фургон",
        brand: "Ford",
        model: "Transit",
        year: 2022,
        name: "Ford Transit",
        price: 32000,
        mileage: 30000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Київ",
        image: require("@/assets/trucks/01.jpg")
    },
    {
        id: 2,
        bodyType: "фургон",
        brand: "Iveco",
        model: "Daily",
        year: 2022,
        name: "Iveco Daily",
        price: 33000,
        mileage: 25000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Львів",
        image: require("@/assets/trucks/02.jpg")
    },
    {
        id: 3,
        bodyType: "фургон",
        brand: "Volkswagen",
        model: "Crafter",
        year: 2022,
        name: "Volkswagen Crafter",
        price: 33000,
        mileage: 28000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Одеса",
        image: require("@/assets/trucks/03.jpg")
    },
    {
        id: 4,
        bodyType: "фургон",
        brand: "Renault",
        model: "Master",
        year: 2020,
        name: "Renault Master",
        price: 31000,
        mileage: 29000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Харків",
        image: require("@/assets/trucks/04.jpg")
    },
    {
        id: 5,
        bodyType: "фургон",
        brand: "Peugeot",
        model: "Boxer",
        year: 2020,
        name: "Peugeot Boxer",
        price: 30000,
        mileage: 27000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Дніпро",
        image: require("@/assets/trucks/05.jpg")
    },
    {
        id: 6,
        bodyType: "фургон",
        brand: "Fiat",
        model: "Ducato",
        year: 2019,
        name: "Fiat Ducato",
        price: 29000,
        mileage: 26000,
        engineType: "дизель",
        transmission: "автомат",
        city: "Запоріжжя",
        image: require("@/assets/trucks/06.jpg")
    }
];
